### ISSUE TITLE
Wrong link sent

### ISSUE THREAD

**Issue by frikimanHD** [269Seahorse/Better-taiko-web#1]
﻿###### 下記の問題を説明してください。 スクリーンショットと診断情報を含めてください。
###### Describe the problem you are having below. Please include a screenshot and the diagnostic information.
Hello, I'm the person who suggested the song Reason from Yuzu (the third ending from Hunter x Hunter 2011), and after playing the song that was recently added I realized the catastrophic mistake I made, I sent the wrong link to the song in the poll. So here is the correct link: https://www.youtube.com/watch?v=PiMAAY3iOMk
Thanks a lot for the effort and I'm really sorry for the mistake.

**Comment by 269Seahorse** [comment]
no problem
