### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KndckLmr** [269Seahorse/Better-taiko-web#5]
![image](https://github.com/269Seahorse/Better-taiko-web/assets/132595817/958855bc-dd5e-4b43-b69d-5872d5add2dc)
refreshing does nothing

**Comment by 269Seahorse** [comment]
This error didn't occur on my side. Can you try going to https://ouo.269seahorse.me/src/js/plugin/ese.taikoweb.js and press shift + F5 to force refresh and try again? Thank you.

**Comment by KndckLmr** [comment]
hello,
the website was working for awhile without this error, however after being disconnected from my wifi and going back to the website again, the website showed the same error. i tried the fix you provided but it did not work

**Comment by 269Seahorse** [comment]
Thank you for your reply. However, I have tested on multiple devices, and shared the site to some other people, no one had this error. Maybe you have to clear your browser's cache to re-read the files again. Thanks!

**Comment by KndckLmr** [comment]
Hello,
thanks for the suggestion, however after clearing my browser cache, it still does not work

**Comment by 269Seahorse** [comment]
Hello,

I am so sorry that I'm afraid that I couldn't solve your issue. I've tested on many operating systems and browsers, but never meet issues.

Sorry for your convenience.
