### ISSUE TITLE
Can you share your song package?

### ISSUE THREAD

**Issue by ZerQAQ** [269Seahorse/Better-taiko-web#6]
Hi,

can you share your song package in https://ouo.269seahorse.me/ ?
song package mean .tja and the corresponding .ogg or .mp3 file

**Comment by 269Seahorse** [comment]
Hello, 

The download song function is available in plugins. Once enabled, you will be able to see the download button in difficulty select area.

Hope this solved your problem.

**Comment by ZerQAQ** [comment]
thank for your respond, but I want to download every song in this web in one action

**Comment by 269Seahorse** [comment]
Hello,

Sorry, there is currently no way to download all songs at a time at this moment. The original zip containing songs was deleted to save storage space.

However, there are many tools for taiko web on github, maybe there is one that fits your need.

**Comment by ZerQAQ** [comment]
I find that I can download tja and ogg/mp3 file throw these url:
```
https://ouo.269seahorse.me/songs/{id}/main.tja
https://ouo.269seahorse.me/songs/{id}/main.ogg
https://ouo.269seahorse.me/songs/{id}/main.mp3
```
Is there a songs floder in the server that contain every song?
can your share that folder to me?

**Comment by 269Seahorse** [comment]
Hello,

For security reasons, that's not possible for me to do that.

**Comment by ZerQAQ** [comment]
also I find this web will download a "music_info.json" file, but it does not contain every songs info I download from the url I mention before, I want to get the category info of every song. Is there any good way to do that?

**Comment by 269Seahorse** [comment]
Hello,

I've found this tool on github, maybe this can help you?
https://github.com/purerosefallen/taiko-grabber

However, there are some songs that I'm not sure if the original charter is ok for sharing to other people, so I still recommend only download the song you need.

**Comment by 269Seahorse** [comment]
Hello,

Join this server and there is a website containing all songs: https://discord.gg/tjadb

I will close this issue with this comment, thank you.
