### ISSUE TITLE
how do I set it up?

### ISSUE THREAD

**Issue by appakling** [269Seahorse/Better-taiko-web#7]
no screenshot needed, the wiki has no information, and dumbasses like me cannot set up this for a website to save my life :(

**Comment by appakling** [comment]
edit holy shit I am just an idiot, setup.md evaded my eyes
sorry :/

**Comment by 269Seahorse** [comment]
Hello,

I've updated the readme.md, the setup page is now linked to the setup.md file.

Sorry for the inconvenience.

Thank you.
